export const CARD_INFO = {
  groomName: "Moh. Shahid Khan",
  groomFather: "Ikbal Khan",
  groomMother: "Farjana Begum",
  brideName: "Khushbu Banu",
  brideFather: "Ikramuddin Quazi",
  brideMother: "Shabana Begum",
  nikahDate: "2026-10-11",
  flowerCarnivalDate: "2026-10-09",
  flowerCarnivalTime: "5:00 PM",
  baratDepartureDate: "2026-10-10",
  baratDepartureTime: "2:00 PM",
  mayraDate: "2026-10-11",
  mayraTime: "11:00 AM",
  receptionAndDinnerDate: "2026-10-11",
  receptionAndDinnerTime: "6:00 PM Onwards",
  resortLocation: "Sundaram Resort",
  resortLandmark: "Harni Mahadev road, Bhilwara",
};
